
package com.lms.wsim;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.naming.spi.ObjectFactory;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "JwsServiceHello", targetNamespace = "http://webService.design.lms.com/")
public interface JwsServiceHello {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getValue", targetNamespace = "http://webService.design.lms.com/", className = "com.lms.design.webservice.GetValue")
    @ResponseWrapper(localName = "getValueResponse", targetNamespace = "http://webService.design.lms.com/", className = "com.lms.design.webservice.GetValueResponse")
    public String getValue(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
